cloud-barista/cb-mapui

- index.js
- CB-Tumblebug v0.2.8 에 맞게 API 콜 수정
- 애러 수정 등
> Apply cb-tumblebug v0.2.8

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/general-question.md
These files are from [CB-Tumblebug](https://github.com/cloud-barista/cb-tumblebug/tree/main/.github/ISSUE_TEMPLATE). 😊
> Add GitHub issue templates

- index.js
Change font size for Suspended status
> Change font size for Suspended status

- index.html
- index.js
- TB MCIS ID 입력란 추가
- MCIS control 버튼 및 기능 추가
- Refine
- Suspend
- Resume
- Reboot
- Terminate
(Refine 버튼은 TB 이슈 https://github.com/cloud-barista/cb-tumblebug/issues/755 가 resolve 되면 정상 동작 예정)
> Add MCIS control feature

- index.html
- index.js
- package-lock.json
- MCIS 제어 등 출력 메시지 제공 (TextArea)
- Recommend MCIS 구성 메시지 변경 (TextArea)
- TextArea에 MCIS 구성 메시지 추가시, 가장 최신 항목으로 자동 스크롤 (TextArea 크기는 3줄로 유지)
- MCIS 생성 후, MCIS 리스트 업데이트
- MCIS 삭제 후, MCIS 리스트 업데이트
> Enhance UI

- .gitignore
- index.html
- index.js
- package-lock.json
- package.json
- Resolves https://github.com/cloud-barista/cb-mapui/pull/19#discussion_r753841150
- Related with https://github.com/cloud-barista/cb-mapui/pull/19#discussion_r753841245
- 훔.. 어떻게 해야 할지 모르겠네요..
일단은 `map.render();` 를 `getMcis();` 로 바꿨습니다. 이후 refresh 주기에 도달하면 맵이 업데이트 될 것입니다.
(그런데 현재도 refresh 주기에 도달하면 어차피 `getMcis();` 가 실행될 것이라서, 
이 PR에서 추가하는 `getMcis();` 코드는 필요가 없네요 😅)
> Fix `ClearMap()`

- index.html
- index.js
- temporal mock ui for demonstration
> Add mock app deploy ui

- index.html
- index.js
> Add display registerd cloud list

- .htmlnanorc
- index.html
- index.js
Ubuntu 18.04 desktop + Firefox 94.0 에서는 출력 & 동작이 정상적으로 되지 않습니다.
Ubuntu 18.04 desktop + Chrome 96.0.4664.45 에서는 정상적으로 출력 & 동작합니다.
(그런데 이 환경에서는 drag to move map 이 동작하지 않습니다 🤔)
> Add vCPU & RAM sliders

- index.html
- index.js
> Add cloud icon for tencent and ibm with enhanced ui

- index.js
> Change icon size

- index.js
- package-lock.json
> Add vmGroupSize prompt

- index.js
MCIS VM Spec 요소 추천시, 
- 확인 팝업에서, 취소하면 선택된 VM Spec이 추가되지 않도록 처리
- 숫자 이외의 다른 값에 대한 예외 처리
MCIS 생성 요청시, 
- 사용자 최종 확인 팝업 추가
> Add confirmation for mcis select create

- index.js
- package-lock.json
- package.json
- sweetalert2 (MIT 라이선스) https://sweetalert2.github.io/ 연동 환경 설정
- 기본 예시 추가
Dockerfile로 생성한 image를 통해서도 문제 없이 구동 됨을 확인하였습니다.
> Apply sweetalert2 for alerts

- Dockerfile
- package-lock.json
- package.json
Fixes https://github.com/cloud-barista/cb-mapui/pull/49#issuecomment-1131524097
> Enhance `Dockerfile` & Update deps

- index.js
- MCIS 제어 버튼 오류 수정 (지난 PR에 의해 실수로 request 종료 구문이 사라짐^^;; )
- MCIS 상태 표시 형태 일부 개선
> Fix mcis control error

- index.js
> Adopt SweetAlert2 for prompt & confirm dialog

- index.js
(Reported by @powerkimhub)
[As-is]
"Total CSP regions:" 체크박스의 체크-해제를 반복할 때마다
"[Complete] Display Known Cloud Regions:" 숫자가 계속 증가함
[To-be]
"Total CSP regions:" 체크박스의 체크-해제를 반복해도
"[Complete] Display Known Cloud Regions:" 숫자가 161개로 표시됨
> Fix bug on "Total-CSP-regions" checkbox

- index.html
- index.js
- Hide/Show MCIS 
- Modifying MCIS name
> Hide/Showing MCIS and modifying MCIS name

- index.js
Signed-off-by: seokho-son <shsongist@gmail.com>
> Remove duplicated getMcis call

- index.html
- index.js
> Enable Image selection for MCIS

- index.html
- index.js
Add input UI for changing root disk size
> Add input UI for changing root disk size

- index.html
- index.js
> Add remote command feature

- index.html
- index.js
- 'Register resources', 'Release default res' 버튼을 1칸씩 위로 올렸습니다.
- 'Get VMGroup' 버튼을 누르면, 현재 선택된 MCIS의 VMGroup 목록을 가져와서 select 객체에 표시합니다.
- 'Add NLB' 버튼을 누르면, 현재 선택된 VMGroup + 현재 입력된 포트 정보를 사용하여 해당 VMGroup에 NLB를 생성합니다.
- 'Del NLB' 버튼을 누르면 현재 선택된 VMGroup에 대한 NLB를 삭제합니다.
> Add 'Create/Delete NLB' feature

- index.js
CB-TB API에서 MCIS 삭제시, 기존 단순 메시지에서 
삭제된 리소스 처리 내역을 제공하는 형태로 변경됨에 따라,
이를 UI에 반영함.
(MCIS 삭제시 출력 예시)
> Apply TB API output message changes

- index.html
- index.js
> Make NS selectable

- index.html
- index.js
- NLB 생성 단계를 팝업으로 추가
- MCIS, SubGroup 등 리스트 조회 버튼을 없애고, 리스트에 마우스 오버하면 조회하도록 개선
- 전반적으로 UI 위치 재조정
> Enhance UI for nlb

- index.js
> Add error handling for NLB

- index.js
> Update naming and index for mcis subgroup

- index.html
- index.js
Add getAccessInfo of MCIS without Key with some UI changes
> Add getAccessInfo of MCIS without Key with some UI changes

- index.js
`"` 및 `,` 를 출력에서 제거하여, text box에서 copy & paste가 쉽도록 개선.
```
[Retrieve access information for MCIS:mc-zhd61]
{
McisId: mc-zhd61
McisSubGroupAccessInfo: [
{
SubGroupId: g1
McisVmAccessInfo: [
{
vmId: g1-1
publicIP: 13.125.25.185
privateIP: 192.168.20.213
sshPort: 22
vmUserAccount: cb-user
}
]
}
]
}
```
> Enhance output message by removing comma

- index.html
- index.js
> Add mc-nlb feature

- index.html
- index.js
> Add weave scope deployment

- index.js
To apply https://github.com/cloud-barista/cb-tumblebug/pull/1292
> Update CB-TB API for register existing

- index.html
- index.js
- package-lock.json
- package.json
> Enhance GUI completely

- index.html
- index.js
- package-lock.json
- package.json
> Update packages and ui

- README.md
based on https://github.com/nodesource/distributions
> Update nodejs install instruction

- index.html
- index.js
- package.json
> Apply displayJsonData style to popup

- index.html
- index.js
- package.json
> Add resource view

- index.html
- index.js
등록된 Connection 리스트를 마우스 오버로 리스팅하고, "Connect" 레이블을 통해 클립보드에 저장할 수 있도록 기능 제공.
> Add handy connection list to UI

- index.html
- index.js
- package.json
- VM의 Public/Private IP 리스트를 자동으로 구성하고,
- 레이블 선택시, 클립보드로 복사하여,
쉽게 VM의 엔드포인트를 복사 및 활용할 수 있도록 UI 제공.
> Add easy to get IP address

- index.js
신규 CSP 추가시, 아이콘만 추가하면 동작하도록 범용 형태로 변경.
> Supporting a new CSP to the map

- index.js
- package.json
[Staging v0.8.8](https://github.com/cloud-barista/cb-mapui/commit/114938ba318e9bdd2948ef5441795851d8e08421)
> Use dynamic hostname for admin web

- index.html
- index.js
- package.json
Apply modified recommend api and Support GPU recommend
> Apply modified recommend api and Support GPU recommend

- package.json
to make server accessible from docker public.
> Open server access to 0.0.0.0

- README.md
- index.html
- index.js
- package.json
- to support https://github.com/cloud-barista/cb-tumblebug/pull/1567
> Add MCIS dynamic hold continue withdraw UI

- index.js
> Shuffle csp icons in the same location

- index.js
- mcis info is more useful here.
> Change mcis status to info

- index.html
- index.js
- package.json
- Support LLM ollama and CB-TB built-in function example
> Support LLM ollama and CB-TB built-in function example

- index.html
- index.js
> Make Provider is selectable for both UI and func

- index.html
- index.js
> Enhance LLM deploy UI

- index.js
to be aligned with cb-tb api changes
> Remove label part

- index.html
- index.js
> Add remote file transfer UI

- index.js
> Popup for verifying and updating cloud connection

- package-lock.json
- package.json
- updated parcel version to fix  arm64 build issue
- update all related dependencies
> Fix arm64 build issue and update depds

- index.js
> Add post command in mci provisioning

- index.js
Add label ui for mc-infra provisioning
> Add label ui for mc-infra provisioning

- index.js
> Add predefined scripts execution in remote cmd

- index.js
* Replaced VPN Gateway Info with VPN sites in Tumblebug
- ref: https://github.com/cloud-barista/cb-tumblebug/blob/0ea92f9c57e99a0089b950dea94aab2f27889ff1/src/core/model/vpn.go#L145
> Align with VpnInfo object in Tumblebug

- index.js
- Add support for basic OS images (isBasicImage field)
- Replace separate ML/K8s columns with unified Support column using icons
- Add visual indicators: ⭐ for basic images, 🧮 for GPU support, ☸️ for K8s support
- Implement special styling for basic image rows (yellow background)
- Optimize table column widths for better layout
- Add icon visual effects with text shadows
- Display basic image status in image details section
- Improve DataTable configuration with proper column sorting
> feat: enhance image selection UI with basic image support and improved icons

- index.html
- index.js
- Add Update Firewall button to main UI for easy access
- Implement complete firewall rules CRUD operations with individual SG management
- Add tab-based interface for managing multiple security groups simultaneously
- Support protocol-specific input validation (ICMP/ALL protocols hide port fields)
- Include preset rules for common configurations (SSH, HTTP, HTTPS, All TCP/UDP ports)
- Provide detailed batch update results with success/failure tracking
- Add individual rule add/delete functionality within existing SG tables
- Integrate with new backend API using TbSecurityGroupUpdateReq format
- Fix disk size validation to handle "0" value in VM spec recommendations
- Support parallel processing for bulk updates with comprehensive error handling
> feat: implement comprehensive security group firewall rules management

- index.js
- to apply https://github.com/cloud-barista/cb-tumblebug/pull/2101
> Update for API changes

- index.html
- index.js
> Dynamically control mci configuration

- index.html
- index.js
> Add convex hull for subgroup configs

- dashboard.html
- dashboard.js
- index.html
- index.js
- k8s error handling within mapui. (but the issue needs to be resolved by backend...)
> Enhance stability for dashboard
